$('.owl-carousel').owlCarousel({
    loop:true,
    margin:0,
    nav:true,
    responsive:{
        1510:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})